server:
  port: 8513

spring:
  jpa:
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://mysql-standalone:4406/test
    username: sa
    password: password